#ifndef CYGONCE_PKGCONF_FS_YAFFS_H
#define CYGONCE_PKGCONF_FS_YAFFS_H
/*
 * File <pkgconf/fs_yaffs.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGPKG_FS_YAFFS_OPTIONS 1
#define CYGSEM_FS_YAFFS_SMALLPAGE_MODE YAFFS2
#define CYGSEM_FS_YAFFS_SMALLPAGE_MODE_YAFFS2
#define CYGSEM_FS_YAFFS_CACHE_SHORT_NAMES 1
#define CYGSEM_FS_YAFFS_OMIT_YAFFS1_CODE 1
#define CYGPKG_FS_YAFFS_RET_DIRENT_DTYPE 1
#define CYGNUM_FS_YAFFS_RESERVED_BLOCKS 5
#define CYGNUM_FS_YAFFS_RESERVED_BLOCKS_5
#define CYGNUM_FS_YAFFS_SHORTOP_CACHES 10
#define CYGNUM_FS_YAFFS_SHORTOP_CACHES_10
#define CYGNUM_FS_YAFFS_TEMP_BUFFERS 7
#define CYGNUM_FS_YAFFS_TEMP_BUFFERS_7
#define CYGNUM_FS_YAFFS_TRACEMASK 5
#define CYGNUM_FS_YAFFS_TRACEMASK_5
#define CYGSEM_FS_YAFFS_TRACEFN diag_printf
#define CYGSEM_FS_YAFFS_TRACEFN_diag_printf
#define CYGSEM_FS_YAFFS_COMPATIBILITY 1
#define CYGPKG_FS_YAFFS_TESTING 1
#define CYGDAT_YAFFS_DEVS_DISK_TEST_DEVICE "onboard/0"
#define CYGDAT_YAFFS_DEVS_DISK_TEST_MOUNTPOINT "/nand"
#define CYGDAT_YAFFS_DEVS_DISK_TEST_DIRECTORY "/test"
#define CYGDAT_YAFFS_DEVS_DISK_TEST_DEVICE2 "onboard/1"
#define CYGDAT_YAFFS_DEVS_DISK_TEST_MOUNTPOINT2 "/nand2"
#define CYGDAT_YAFFS_DEVS_DISK_TEST_DIRECTORY2 "/test"

#endif
