#ifndef CYGONCE_PKGCONF_HAL_FREESCALE_EDMA_H
#define CYGONCE_PKGCONF_HAL_FREESCALE_EDMA_H
/*
 * File <pkgconf/hal_freescale_edma.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_HAL_FREESCALE_EDMA_CHAN_NUM 32
#define CYGNUM_HAL_FREESCALE_EDMA_CHAN_NUM_32
#define CYGOPT_HAL_FREESCALE_EDMA_EMLM 1
#define CYGNUM_HAL_FREESCALE_EDMA_GROUP_SIZE 16
#define CYGNUM_HAL_FREESCALE_EDMA_GROUP_SIZE_16
#define CYGNUM_HAL_FREESCALE_EDMA_GROUP_NUM 2
#define CYGNUM_HAL_FREESCALE_EDMA_GROUP_NUM_2
#define CYGNUM_HAL_FREESCALE_EDMA_GR0_PRIO 0
#define CYGNUM_HAL_FREESCALE_EDMA_GR0_PRIO_0
#define CYGNUM_HAL_FREESCALE_EDMA_GR1_PRIO 1
#define CYGNUM_HAL_FREESCALE_EDMA_GR1_PRIO_1
#define CYGNUM_HAL_FREESCALE_DMAMUX_CHAN_NUM 16
#define CYGNUM_HAL_FREESCALE_DMAMUX_CHAN_NUM_16
#define CYGNUM_HAL_FREESCALE_DMAMUX_NUM 2
#define CYGNUM_HAL_FREESCALE_DMAMUX_NUM_2

#endif
