#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_CORTEXM current
#define CYGPKG_HAL_CORTEXM_current
#define CYGNUM_HAL_CORTEXM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_VERSION_RELEASE -1
#define CYGBLD_HAL_LIBM_H <cyg/hal/fpv4_sp_d16_libm.h>
#define CYGBLD_HAL_ENDIAN_H <cyg/hal/cortexm_endian.h>
#define CYGPKG_HAL_CORTEXM_KINETIS current
#define CYGPKG_HAL_CORTEXM_KINETIS_current
#define CYGNUM_HAL_CORTEXM_KINETIS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_KINETIS_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_KINETIS_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_cortexm.h>
#define CYGBLD_HAL_VARIANT_H  <pkgconf/hal_cortexm_kinetis.h>
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_kinetis_flash_unisram_extram_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_kinetis_flash_unisram_extram_ram.h>
#define CYGPKG_HAL_CORTEXM_KINETIS_CORE_K70F150M current
#define CYGPKG_HAL_CORTEXM_KINETIS_CORE_K70F150M_current
#define CYGNUM_HAL_CORTEXM_KINETIS_CORE_K70F150M_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_KINETIS_CORE_K70F150M_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_KINETIS_CORE_K70F150M_VERSION_RELEASE -1
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_cortexm_kinetis_core_k70f150m.h>
#define CYGPRI_KERNEL_TESTS_DHRYSTONE_PASSES 4000000
#define CYGPKG_HAL_FREESCALE_EDMA current
#define CYGPKG_HAL_FREESCALE_EDMA_current
#define CYGNUM_HAL_FREESCALE_EDMA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_FREESCALE_EDMA_VERSION_MINOR -1
#define CYGNUM_HAL_FREESCALE_EDMA_VERSION_RELEASE -1
#define CYGPKG_IO_SERIAL_FREESCALE_UART_HDR current
#define CYGPKG_IO_SERIAL_FREESCALE_UART_HDR_current
#define CYGNUM_IO_SERIAL_FREESCALE_UART_HDR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SERIAL_FREESCALE_UART_HDR_VERSION_MINOR -1
#define CYGNUM_IO_SERIAL_FREESCALE_UART_HDR_VERSION_RELEASE -1
/***** serial driver proc output start *****/
#define CYGDAT_IO_SERIAL_DEVICE_HDR_HEADER <pkgconf/io_serial_freescale_uart_hdr.h>
/*****  serial driver proc output end  *****/
#define CYGPKG_IO_SERIAL_FREESCALE_UART current
#define CYGPKG_IO_SERIAL_FREESCALE_UART_current
#define CYGNUM_IO_SERIAL_FREESCALE_UART_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SERIAL_FREESCALE_UART_VERSION_MINOR -1
#define CYGNUM_IO_SERIAL_FREESCALE_UART_VERSION_RELEASE -1
/***** serial driver proc output start *****/
#define CYGDAT_IO_SERIAL_DEVICE_HEADER <pkgconf/io_serial_freescale_uart.h>
/*****  serial driver proc output end  *****/
#define CYGPKG_DEVS_ETH_PHY current
#define CYGPKG_DEVS_ETH_PHY_current
#define CYGNUM_DEVS_ETH_PHY_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_ETH_PHY_VERSION_MINOR -1
#define CYGNUM_DEVS_ETH_PHY_VERSION_RELEASE -1
#define CYGPKG_DEVS_ETH_FREESCALE_ENET current
#define CYGPKG_DEVS_ETH_FREESCALE_ENET_current
#define CYGNUM_DEVS_ETH_FREESCALE_ENET_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_ETH_FREESCALE_ENET_VERSION_MINOR -1
#define CYGNUM_DEVS_ETH_FREESCALE_ENET_VERSION_RELEASE -1
#define CYGPKG_IO_SPI current
#define CYGPKG_IO_SPI_current
#define CYGNUM_IO_SPI_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SPI_VERSION_MINOR -1
#define CYGNUM_IO_SPI_VERSION_RELEASE -1
#define CYGPKG_DEVS_SPI_FREESCALE_DSPI current
#define CYGPKG_DEVS_SPI_FREESCALE_DSPI_current
#define CYGNUM_DEVS_SPI_FREESCALE_DSPI_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_SPI_FREESCALE_DSPI_VERSION_MINOR -1
#define CYGNUM_DEVS_SPI_FREESCALE_DSPI_VERSION_RELEASE -1
#define CYGPKG_DEVS_AUDIO_FREESCALE_DSPI current
#define CYGPKG_DEVS_AUDIO_FREESCALE_DSPI_current
#define CYGNUM_DEVS_AUDIO_FREESCALE_DSPI_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_AUDIO_FREESCALE_DSPI_VERSION_MINOR -1
#define CYGNUM_DEVS_AUDIO_FREESCALE_DSPI_VERSION_RELEASE -1
#define CYGPKG_DEVS_SND_VS1063A current
#define CYGPKG_DEVS_SND_VS1063A_current
#define CYGNUM_DEVS_SND_VS1063A_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_SND_VS1063A_VERSION_MINOR -1
#define CYGNUM_DEVS_SND_VS1063A_VERSION_RELEASE -1
/***** AUDIO/SPI driver output start *****/
#ifndef CYGDAT_DEVS_AUDIO_CFG
#define CYGDAT_DEVS_AUDIO_CFG <pkgconf/devs_snd_vs1063.h>
#endif
/***** AUDIO/SPI driver output end *****/
#define CYGPKG_DEVS_NAND_FSL_KINETIS_NFC current
#define CYGPKG_DEVS_NAND_FSL_KINETIS_NFC_current
#define CYGNUM_DEVS_NAND_FSL_KINETIS_NFC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_NAND_FSL_KINETIS_NFC_VERSION_MINOR -1
#define CYGNUM_DEVS_NAND_FSL_KINETIS_NFC_VERSION_RELEASE -1
#define CYGPKG_IO_I2C current
#define CYGPKG_IO_I2C_current
#define CYGNUM_IO_I2C_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_I2C_VERSION_MINOR -1
#define CYGNUM_IO_I2C_VERSION_RELEASE -1
#define CYGPKG_DEVS_I2C_FREESCALE_I2C current
#define CYGPKG_DEVS_I2C_FREESCALE_I2C_current
#define CYGNUM_DEVS_I2C_FREESCALE_I2C_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_I2C_FREESCALE_I2C_VERSION_MINOR -1
#define CYGNUM_DEVS_I2C_FREESCALE_I2C_VERSION_RELEASE -1
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_IO current
#define CYGPKG_IO_current
#define CYGNUM_IO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_VERSION_MINOR -1
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_IO_SERIAL current
#define CYGPKG_IO_SERIAL_current
#define CYGNUM_IO_SERIAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SERIAL_VERSION_MINOR -1
#define CYGNUM_IO_SERIAL_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL current
#define CYGPKG_KERNEL_current
#define CYGNUM_KERNEL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_KERNEL_VERSION_MINOR -1
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC current
#define CYGPKG_MEMALLOC_current
#define CYGNUM_MEMALLOC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_MEMALLOC_VERSION_MINOR -1
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC current
#define CYGPKG_LIBC_current
#define CYGNUM_LIBC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_VERSION_MINOR -1
#define CYGNUM_LIBC_VERSION_RELEASE -1
#define CYGPKG_LIBC_I18N current
#define CYGPKG_LIBC_I18N_current
#define CYGNUM_LIBC_I18N_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_I18N_VERSION_MINOR -1
#define CYGNUM_LIBC_I18N_VERSION_RELEASE -1
#define CYGPKG_LIBC_SETJMP current
#define CYGPKG_LIBC_SETJMP_current
#define CYGNUM_LIBC_SETJMP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_SETJMP_VERSION_MINOR -1
#define CYGNUM_LIBC_SETJMP_VERSION_RELEASE -1
#define CYGPKG_LIBC_STARTUP current
#define CYGPKG_LIBC_STARTUP_current
#define CYGNUM_LIBC_STARTUP_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STARTUP_VERSION_MINOR -1
#define CYGNUM_LIBC_STARTUP_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDIO current
#define CYGPKG_LIBC_STDIO_current
#define CYGNUM_LIBC_STDIO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STDIO_VERSION_MINOR -1
#define CYGNUM_LIBC_STDIO_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDLIB current
#define CYGPKG_LIBC_STDLIB_current
#define CYGNUM_LIBC_STDLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STDLIB_VERSION_MINOR -1
#define CYGNUM_LIBC_STDLIB_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_LIBC_TIME current
#define CYGPKG_LIBC_TIME_current
#define CYGNUM_LIBC_TIME_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_TIME_VERSION_MINOR -1
#define CYGNUM_LIBC_TIME_VERSION_RELEASE -1
#define CYGPKG_LIBM current
#define CYGPKG_LIBM_current
#define CYGNUM_LIBM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBM_VERSION_MINOR -1
#define CYGNUM_LIBM_VERSION_RELEASE -1
#define CYGPKG_POSIX current
#define CYGPKG_POSIX_current
#define CYGNUM_POSIX_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_POSIX_VERSION_MINOR -1
#define CYGNUM_POSIX_VERSION_RELEASE -1
#define CYGPKG_IO_WALLCLOCK current
#define CYGPKG_IO_WALLCLOCK_current
#define CYGNUM_IO_WALLCLOCK_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_WALLCLOCK_VERSION_MINOR -1
#define CYGNUM_IO_WALLCLOCK_VERSION_RELEASE -1
#define CYGPKG_ERROR current
#define CYGPKG_ERROR_current
#define CYGNUM_ERROR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ERROR_VERSION_MINOR -1
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_IO_FILEIO current
#define CYGPKG_IO_FILEIO_current
#define CYGNUM_IO_FILEIO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_FILEIO_VERSION_MINOR -1
#define CYGNUM_IO_FILEIO_VERSION_RELEASE -1
#define CYGPKG_NET current
#define CYGPKG_NET_current
#define CYGNUM_NET_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_NET_VERSION_MINOR -1
#define CYGNUM_NET_VERSION_RELEASE -1
#define CYGPKG_NET_FREEBSD_STACK current
#define CYGPKG_NET_FREEBSD_STACK_current
#define CYGNUM_NET_FREEBSD_STACK_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_NET_FREEBSD_STACK_VERSION_MINOR -1
#define CYGNUM_NET_FREEBSD_STACK_VERSION_RELEASE -1
/***** Networking stack proc output start *****/
#define CYGDAT_NET_STACK_CFG <pkgconf/net_freebsd_stack.h>
/***** Networking stack proc output end *****/
#define CYGPKG_SNMPAGENT current
#define CYGPKG_SNMPAGENT_current
#define CYGNUM_SNMPAGENT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_SNMPAGENT_VERSION_MINOR -1
#define CYGNUM_SNMPAGENT_VERSION_RELEASE -1
#define CYGPKG_SNMPLIB current
#define CYGPKG_SNMPLIB_current
#define CYGNUM_SNMPLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_SNMPLIB_VERSION_MINOR -1
#define CYGNUM_SNMPLIB_VERSION_RELEASE -1
#define CYGPKG_NS_DNS current
#define CYGPKG_NS_DNS_current
#define CYGNUM_NS_DNS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_NS_DNS_VERSION_MINOR -1
#define CYGNUM_NS_DNS_VERSION_RELEASE -1
#define CYGPKG_IO_ETH_DRIVERS current
#define CYGPKG_IO_ETH_DRIVERS_current
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MINOR -1
#define CYGNUM_IO_ETH_DRIVERS_VERSION_RELEASE -1
#define CYGPKG_CRC current
#define CYGPKG_CRC_current
#define CYGNUM_CRC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CRC_VERSION_MINOR -1
#define CYGNUM_CRC_VERSION_RELEASE -1
#define CYGPKG_CPULOAD current
#define CYGPKG_CPULOAD_current
#define CYGNUM_CPULOAD_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CPULOAD_VERSION_MINOR -1
#define CYGNUM_CPULOAD_VERSION_RELEASE -1
#define CYGPKG_LINUX_COMPAT current
#define CYGPKG_LINUX_COMPAT_current
#define CYGNUM_LINUX_COMPAT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LINUX_COMPAT_VERSION_MINOR -1
#define CYGNUM_LINUX_COMPAT_VERSION_RELEASE -1
#define CYGPKG_NET_FTPCLIENT current
#define CYGPKG_NET_FTPCLIENT_current
#define CYGNUM_NET_FTPCLIENT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_NET_FTPCLIENT_VERSION_MINOR -1
#define CYGNUM_NET_FTPCLIENT_VERSION_RELEASE -1
#define CYGPKG_COMPRESS_ZLIB current
#define CYGPKG_COMPRESS_ZLIB_current
#define CYGNUM_COMPRESS_ZLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_COMPRESS_ZLIB_VERSION_MINOR -1
#define CYGNUM_COMPRESS_ZLIB_VERSION_RELEASE -1
#define CYGPKG_IO_DISK current
#define CYGPKG_IO_DISK_current
#define CYGNUM_IO_DISK_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_DISK_VERSION_MINOR -1
#define CYGNUM_IO_DISK_VERSION_RELEASE -1
#define CYGPKG_BLOCK_LIB current
#define CYGPKG_BLOCK_LIB_current
#define CYGNUM_BLOCK_LIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_BLOCK_LIB_VERSION_MINOR -1
#define CYGNUM_BLOCK_LIB_VERSION_RELEASE -1
#define CYGPKG_EZXML current
#define CYGPKG_EZXML_current
#define CYGNUM_EZXML_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_EZXML_VERSION_MINOR -1
#define CYGNUM_EZXML_VERSION_RELEASE -1
#define CYGPKG_IO_NAND current
#define CYGPKG_IO_NAND_current
#define CYGNUM_IO_NAND_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_NAND_VERSION_MINOR -1
#define CYGNUM_IO_NAND_VERSION_RELEASE -1
#define CYGPKG_FS_YAFFS v1_2_1
#define CYGPKG_FS_YAFFS_v1_2_1
#define CYGNUM_FS_YAFFS_VERSION_MAJOR 1
#define CYGNUM_FS_YAFFS_VERSION_MINOR 2
#define CYGNUM_FS_YAFFS_VERSION_RELEASE 1
/***** Synthdisk driver proc output start *****/
#define CYGDAT_YAFFS_DEVS_DISK_CFG <pkgconf/fs_yaffs.h>
/***** Synthdisk driver proc output end  *****/
#define CYGPKG_IO_AUDIO current
#define CYGPKG_IO_AUDIO_current
#define CYGNUM_IO_AUDIO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_AUDIO_VERSION_MINOR -1
#define CYGNUM_IO_AUDIO_VERSION_RELEASE -1
#define CYGPKG_IO_WATCHDOG current
#define CYGPKG_IO_WATCHDOG_current
#define CYGNUM_IO_WATCHDOG_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_WATCHDOG_VERSION_MINOR -1
#define CYGNUM_IO_WATCHDOG_VERSION_RELEASE -1

#endif
