#ifndef CYGONCE_PKGCONF_IO_NAND_H
#define CYGONCE_PKGCONF_IO_NAND_H
/*
 * File <pkgconf/io_nand.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGSEM_IO_NAND_APPINTERFACE_VERSION 2
#define CYGSEM_IO_NAND_APPINTERFACE_VERSION_2
#define CYGSEM_IO_NAND_INTERFACE_VERSION 2
#define CYGSEM_IO_NAND_INTERFACE_VERSION_2
#define CYGPKG_IO_NAND_OPTIONS 1
#define CYGHWR_IO_NAND_DEVICE 1
#define CYGHWR_IO_NAND_DEVICE_1
#define CYGSEM_IO_NAND_DEBUG 1
#define CYGSEM_IO_NAND_DEBUG_FN_DEFAULT cyg_nand_defaultprintf
#define CYGSEM_IO_NAND_DEBUG_FN_DEFAULT_cyg_nand_defaultprintf
#define CYGSEM_IO_NAND_DEBUG_LEVEL 5
#define CYGSEM_IO_NAND_DEBUG_LEVEL_5
#define CYGSEM_IO_NAND_USE_BBT 1
#define CYGNUM_NAND_PAGEBUFFER 2048
#define CYGNUM_NAND_PAGEBUFFER_2048
#define CYGNUM_NAND_MAX_READ_RETRIES 2
#define CYGNUM_NAND_MAX_READ_RETRIES_2
#define CYGNUM_NAND_MAX_PARTITIONS 4
#define CYGNUM_NAND_MAX_PARTITIONS_4
#define CYGSEM_IO_NAND_INSTRUMENT_TIMING 1
#define CYGNUM_IO_NAND_TEST_PARTITION 1
#define CYGNUM_IO_NAND_TEST_PARTITION_1

#endif
